# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

before:
  hooks:
    - go mod tidy

project_name: go-check-updates

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
  description: A Go-first dependency management utility
  full_description: |-
    A Go-first dependency management utility that helps you keep your `go.mod` dependencies up to date with the latest versions available. It scans your `go.mod` file, checks for newer versions of your dependencies, and provides an easy way to update them while ensuring compatibility with your project.
  homepage: https://github.com/pragmaticivan/go-check-updates
  license: MIT
  maintainers:
    - Ivan Santos <hello@ivansantos.me>

gomod:
  proxy: true

builds:
  - id: gcu
    main: ./cmd/gcu
    binary: gcu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# homebrew_casks:
#   - repository:
#       owner: pragmaticivan
#       name: homebrew-tap
#     url:
#       verified: github.com/pragmaticivan/go-check-updates
#     hooks:
#       post:
#         install: |
#           if OS.mac?
#             system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-check-updates"]
#           end

# nfpms:
#   - file_name_template: "{{ .ConventionalFileName }}"
#     formats:
#       - apk
#       - deb
#       - rpm
#     bindir: /usr/bin
#     section: utils

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

checksum:
  name_template: "checksums.txt"
